### ISSUE TITLE
Header height is too much

### ISSUE THREAD

**Issue by rukshan99** [rukshan99/rukshan99.github.io#1]
![Screenshot (244)](https://user-images.githubusercontent.com/68691231/111804919-8e8efd00-88f6-11eb-8992-46e832afd19d.png)

**Comment by 96RadhikaJadhav** [comment]
@rukshan99 Can I work on it?

**Comment by rukshan99** [comment]
> @rukshan99 Can I work on it?

yeah sure!

**Comment by 96RadhikaJadhav** [comment]
@rukshan99 Created a PR #2 . Could you please check and let me know if any other changes required.

**Comment by rukshan99** [comment]
> @rukshan99 Created a PR #2 . Could you please check and let me know if any other changes required.

Looks nice. Thanks for the contribution.
